---
- name: update univention apps
  shell:
    cmd: "/usr/bin/univention-app update"
  tags: apps

- name: install apps from appstore
  shell:
    cmd: "/usr/bin/univention-app install {{ item }} --username Administrator --noninteractive --pwdfile {{ rootpwfile.path }}"
  loop: "{{ apps }}"
  tags: apps

- include_tasks: apps.yaml
- include_tasks: openxchange.yaml
- include_tasks: appcenter-dev.yaml
