---
- name: create profile for join
  template:
     src: "templates/profile.j2"
     dest: "/var/cache/univention-system-setup/profile"
  tags: join

- name: create temporary root credentials file
  tempfile:
    state: file
    suffix: temp
  register: rootpwfile
  tags: join

- name: copy password in file
  copy: 
    content: "{{ rootpassword }}"
    dest: "{{ rootpwfile.path }}"
  tags: join

- name: run join script on master
  shell: "/usr/lib/univention-system-setup/scripts/setup-join.sh"
  tags: join


